#ifndef NOCAMERA_H_
#define NOCAMERA_H_

#include <stdint.h>


/* the purpose of this module is to simulate a tracking field without
   the benefit (or hinderence) of using the real camra 

   The idea is you set the image size, and exposure time and the
   guider software calls the nocamera::get_image() function instead of
   the grabber.get_image function. That leads to the guider buffer
   being populated with an image generated by this module -- either
   something loaded from the disk, or just created here. 

   Do not touch the init and close functions, or the core
   variables. You can edit the userinit(), userclose(), and
   usergetimage() functions as you like, along with the uservariables.

   
*/


#define LIBIMAGEDIR "/home/salo/FB/Fireball2/fbguider/bin_v05/img_save/"

namespace nocamera{
  // init or close the "no_camera"
  int init(uint16_t **buffers,uint16_t width, uint16_t height);
  int close();
  void getimage(uint16_t *buf, uint32_t exptime);


  // load images
  // 
  void load_images(uint16_t *buffers);
  
  // user functions
  int userinit();
  int userclose();
  uint16_t usergetimage();
  
  void set_exptime(unsigned int expt);


}; // namespace nocamera

#endif // NOCAMERA_H_
